# Generated by bmbox: runs one virtualbmc IPMI endpoint in the foreground.
# Usage: python ipmi_bmc.py <config.json>
import json
import sys

from virtualbmc.vbmc import VirtualBMC

with open(sys.argv[1]) as f:
    cfg = json.load(f)

bmc = VirtualBMC(
    username=cfg["username"],
    password=cfg["password"],
    port=cfg["port"],
    address=cfg["address"],
    domain_name=cfg["domain"],
    libvirt_uri=cfg["libvirt_uri"],
)
print("bmbox ipmi bmc for %s listening on %s:%d" % (cfg["domain"], cfg["address"], cfg["port"]))
bmc.listen(timeout=30)
