package bmc

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/crypto/bcrypt"
)

// writeRedfish renders a sushy-emulator config restricted to this node's
// domain, plus an htpasswd file for basic auth.
func writeRedfish(s Spec, w FileWriter, t Tools) (cmd []string, changed bool, err error) {
	cfgPath := filepath.Join(s.Dir, "sushy.conf")
	authPath := filepath.Join(s.Dir, "htpasswd")

	// bcrypt salts every hash, so only rewrite when the password changed.
	if !htpasswdMatches(authPath, s.Username, s.Password) {
		hash, err := bcrypt.GenerateFromPassword([]byte(s.Password), bcrypt.DefaultCost)
		if err != nil {
			return nil, false, err
		}
		if err := w.WriteSecret(authPath, []byte(s.Username+":"+string(hash)+"\n")); err != nil {
			return nil, false, err
		}
		changed = true
	}

	q := func(v any) string { b, _ := json.Marshal(v); return string(b) }
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by bmbox for %s/%s. Do not edit.\n", s.Lab, s.Node)
	fmt.Fprintf(&b, "SUSHY_EMULATOR_LISTEN_IP = %s\n", q(s.Address))
	fmt.Fprintf(&b, "SUSHY_EMULATOR_LISTEN_PORT = %d\n", s.Port)
	fmt.Fprintf(&b, "SUSHY_EMULATOR_LIBVIRT_URI = %s\n", q(s.LibvirtURI))
	// One BMC per node: sushy only exposes this domain (by UUID or name).
	fmt.Fprintf(&b, "SUSHY_EMULATOR_ALLOWED_INSTANCES = %s\n", q([]string{s.UUID, s.Domain}))
	fmt.Fprintf(&b, "SUSHY_EMULATOR_AUTH_FILE = %s\n", q(authPath))
	fmt.Fprintf(&b, "SUSHY_EMULATOR_BOOT_LOADER_MAP = {\"UEFI\": {\"x86_64\": %s}, \"Legacy\": {\"x86_64\": None}}\n", q(s.Loader))
	cfg := []byte(b.String())

	if old, err := os.ReadFile(cfgPath); err != nil || !bytes.Equal(old, cfg) {
		if err := w.WriteFile(cfgPath, cfg); err != nil {
			return nil, false, err
		}
		changed = true
	}
	return []string{t.SushyEmulator, "--config", cfgPath}, changed, nil
}

func htpasswdMatches(path, user, password string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	u, hash, ok := strings.Cut(strings.TrimSpace(string(data)), ":")
	return ok && u == user && bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil
}

// probeRedfish succeeds once the node's System resource is served with the
// configured credentials.
func probeRedfish(s Spec) error {
	host := s.Address
	if ip := net.ParseIP(host); ip != nil && ip.IsUnspecified() {
		host = "127.0.0.1"
	}
	url := "http://" + net.JoinHostPort(host, fmt.Sprint(s.Port)) + "/redfish/v1/Systems/" + s.UUID
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	req.SetBasicAuth(s.Username, s.Password)
	resp, err := (&http.Client{Timeout: 3 * time.Second}).Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return nil
}
